"""add file fields to message

Revision ID: 36aa44b842b4
Revises: 55fef17b552f
Create Date: 2026-07-23 17:06:13.050159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36aa44b842b4'
down_revision = '55fef17b552f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_file', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('original_filename')
        batch_op.drop_column('is_file')

    # ### end Alembic commands ###
