"""add sender encrypted key field

Revision ID: 8fcac4b4bda7
Revises: 36aa44b842b4
Create Date: 2026-07-24 05:17:22.805183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcac4b4bda7'
down_revision = '36aa44b842b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enc_aes_key_sender', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('enc_aes_key_sender')

    # ### end Alembic commands ###
