"""add verification, key backup, invites, group chat, file keys

Revision ID: ccb1d834bd5d
Revises: 6829a9040bc8
Create Date: 2026-07-25 03:06:08.040454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb1d834bd5d'
down_revision = '6829a9040bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('invited_user_id', sa.Integer(), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'invited_user_id', name='uq_group_invite')
    )
    op.create_table('group_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wrapped_key', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['shared_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'user_id', name='uq_file_key')
    )
    op.create_table('group_message_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wrapped_key', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['group_message_id'], ['group_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_message_id', 'user_id', name='uq_group_message_key')
    )
    with op.batch_alter_table('public_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enc_private_key_blob', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('sign_private_key_blob', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('kdf_salt', sa.String(length=64), nullable=False))

    with op.batch_alter_table('shared_files', schema=None) as batch_op:
        batch_op.drop_column('enc_aes_key')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('verification_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('failed_login_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['verification_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_count')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('shared_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enc_aes_key', sa.TEXT(), autoincrement=False, nullable=False))

    with op.batch_alter_table('public_keys', schema=None) as batch_op:
        batch_op.drop_column('kdf_salt')
        batch_op.drop_column('sign_private_key_blob')
        batch_op.drop_column('enc_private_key_blob')

    op.drop_table('group_message_keys')
    op.drop_table('file_keys')
    op.drop_table('group_messages')
    op.drop_table('group_invites')
    # ### end Alembic commands ###
